project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Data Science"
  author: "Michael T. Stobb"
  date: "9/7/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - example_notebook.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt



