project:
  type: book
  resources:
    - "data/"
  output-dir: docs

book:
  title: "Introduction to Data Science"
  author: "Michael T. Stobb"
  date: "1/1/2026"
  chapters:
    - index.qmd
    - chapters/01-introduction.qmd

format:
  live-html:
    theme:
      dark: darkly
      light: flatly
    toc: true

filters:
  - live

engine: jupyter
